name: ml-iaifi
channels:
    - pyg
    - pytorch
    - conda-forge
dependencies:
    - python=3.9
    - numpy
    - uproot
    - tensorflow
    - xrootd
    - scikit-learn
    - matplotlib
    - pytorch
    - torchvision
    - torchaudio
    - cpuonly
    - pyg
    - mplhep
    - tqdm
    - autopep8
    - pip
    - pip:
      - jupyter-book
